"""Constants for the Google ADK v2+ integration."""

DEFAULT_MAX_KEY_LENGTH = 128
DEFAULT_MAX_VARCHAR_LENGTH = 256
MIN_GOOGLE_ADK_VERSION = "2.0.0"

__all__ = ("DEFAULT_MAX_KEY_LENGTH", "DEFAULT_MAX_VARCHAR_LENGTH", "MIN_GOOGLE_ADK_VERSION")
