"""Constants mirrored from Google ADK's v1 database schema."""

DEFAULT_MAX_KEY_LENGTH = 128
DEFAULT_MAX_VARCHAR_LENGTH = 256
LATEST_SCHEMA_VERSION = "1"

__all__ = ("DEFAULT_MAX_KEY_LENGTH", "DEFAULT_MAX_VARCHAR_LENGTH", "LATEST_SCHEMA_VERSION")
